### ISSUE TITLE
Hide other images

### ISSUE THREAD

**Issue by freshface** [mathiasbynens/jquery-slideshow#2]
Hi Matthias

Is it possible that the other (not first image) images are still visible?
How could this be fixed? I have this problem: http://cl.ly/489f and http://cl.ly/47xX

JS:

$('.photoGallerySlideshowProjects').slideshow({ timeout: 7000, speed: 600 });

CSS: 
`
.photoGallerySlideshowProjects { position: relative; }
.photoGallerySlideshowProjects div { display: none; position: absolute;}`

HTML https://gist.github.com/789503

**Comment by mathiasbynens** [comment]
Try giving `.photoGallerySlideshowProjects` and `photoGallerySlideshowProjects div` a fixed `height`. To prevent the other images from displaying behind the first one, just give them a `background`.

Also see the demo: http://mathiasbynens.be/demo/slideshow

If that doesn’t help, create a [jsFiddle](http://jsfiddle.net/) instead of sending me all the code separately, and I’ll have a look ;)

**Comment by freshface** [comment]
Thx that does help, only i don't like using a background-color to fix it :)
Isn't it possible to fade-out the other div's? Pretty new to jquery.

**Comment by mathiasbynens** [comment]
This plugin was made to be as compact as possible. It certainly doesn’t satisfy every possible use case.

What you’re suggesting would require a complete rewrite.

I think you’re better off using a plugin like http://malsup.com/jquery/cycle/lite/.
